// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// error
double error(int n, IntegerVector c, IntegerVector es_c);
RcppExport SEXP _SA24204154_error(SEXP nSEXP, SEXP cSEXP, SEXP es_cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type es_c(es_cSEXP);
    rcpp_result_gen = Rcpp::wrap(error(n, c, es_c));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204154_error", (DL_FUNC) &_SA24204154_error, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204154(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
