# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute Community Assignment Error
#' @description Calculate the error between the true community vector and the estimated community vector
#' @param n the length of the input community vector
#' @param c the true community assignment vector
#' @param es_c the estimated community assignment vector
#' @return the computational error between two input vectors
#' @export
error <- function(n, c, es_c) {
    .Call('_SA24204154_error', PACKAGE = 'SA24204154', n, c, es_c)
}

